Add cast for output from FP16 -> FP32; remove remaining casts
DenisVieriu97/executorch pull request #9
Opened 2023-12-13 02:18 UTC by DenisVieriu97

2023-12-13 09:22 UTC, georgepaw requested changes

2023-12-13 09:22 UTC, georgepaw commented on backends/apple/mps/mps_preprocess.py
> +                        out_node = graphNodes.get_node(node.args[i][j].name)
Is there a reason for this change? The casts will be elided by MPSGraph. If you are concerned about these casts, we should instead just change the `get_node` method to default to not doing the cast.

2023-12-15 16:01 UTC, DenisVieriu97 commented on backends/apple/mps/mps_preprocess.py
> +                        out_node = graphNodes.get_node(node.args[i][j].name)
I was seeing additional casts in the graph (from `FP16->FP32`) which were causing lots of overhead

2023-12-15 16:05 UTC, georgepaw commented on backends/apple/mps/mps_preprocess.py
> +                        out_node = graphNodes.get_node(node.args[i][j].name)
Good point - I wasn't expecting this to be a big overhead. In my PR I've removed these and also ensured to only add output casts when the outputs in EdgeIR were FP32

2023-12-15 16:33 UTC, closed without merging